### ISSUE TITLE
Scientists can opt in to research studies and identify how to provide feedback on cellxgene from our website. 

### ISSUE THREAD

**Issue by ambrosejcarr** [chanzuckerberg/single-cell#51]
#### Stories
*Scientists need to be able to tell the single cell team things they like, don't like, or need from cellxgene. They want the option to be obvious, and want it to be in the same spot on each page so that they can easily find it from any page associated with our product*

REQ: Preferred channels are emphasized over non-preferred approaches, but **all channels are offered**. 
REQ: An option exists to provide private feedback. 
REQ: Feedback paths must be enabled for both desktop and hosted versions of cellxgene. 

*The Single Cell team needs scientists who use cellxgene to be able to opt into future research studies so their needs can inform the cellxgene roadmap*

*The Single Cell team needs to be able to contact responding scientists so they can be notified when we've fulfilled their request.*

#### Oustanding Product Questions
- [ ] Decision on which channel we prefer (email, slack, github, twitter). Balance capturing information with guiding users to our preferred contact method(s)
- [ ] Define what information must be collected from users opting into future research. 
- [ ] Decide on email used to collect feedback, if using email.
- [ ] Decide if and how opt-in should be integrated with user accounts

#### See Also
- https://docs.google.com/document/d/1zAg21amiHFhRoBv0gP8BBxXlVVNZeMfN9JusFtqQ1SQ/edit
- [Qualtrics](https://www.qualtrics.com/) for embedding surveys in an iframe (UXRD recommendation)

**Comment by KirstyEwing** [comment]
A couple of other considerations: 
- Who will be on point for responding to any user feedback ? You may want to include the creation of a high-level customer support plan as part of this epic. 
- You may want to split this work into two sub-tasks. One for soliciting ongoing feedback (e.g. updating the email CTA), and another task for embedding a temporary survey link on the cellxgene website for a period of roughly two(?) months. 
- Will likely need to run the proposed plan by Trust XFN since you'll be collecting PII

**Comment by brianraymor** [comment]
@hthomas-czi - this was created for the future UXR person. Can you review with Rina and determine if this is useful for your future work? If not, please close.

**Comment by ambrosejcarr** [comment]
No longer relevant.
