### ISSUE TITLE
Create cellxgene tutorials

### ISSUE THREAD

**Issue by signechambers1** [chanzuckerberg/single-cell#59]
Story: 

_Cellxgene is a power user tool, we'd like to make discovering and using new functionality as easy as possible for our users._

Questions: 
- for which user do we write tutorials? Both "Hosted user - data consumer" and "Desktop user - annotations".
- what workflows will each user want to execute? 
- What do we want the user to learn/be able to do? see [this blog](https://documentation.divio.com/).
- Is the current jekyll/docs and jekyll/gifs representation the appropriate communication medium? 
- How should the tutorials be presented to the user? How are desktop and hosted tutorials differentiated?
- In what order should tutorials be written? 

Prior tutorial suggestions:
- [ ] From neuromusic in https://github.com/chanzuckerberg/cellxgene/issues/729; how to do differential expression / how to find marker genes
- [ ] FACS style gating using scatter plot and brushing multiple distributions [665](https://github.com/chanzuckerberg/cellxgene/issues/665), [937](https://github.com/chanzuckerberg/cellxgene/issues/937)
- [ ] Reembedding
- [ ] Subsetting
- [ ] Explain how to use cellxgene with major data modalities. Initial priority to scRNA-seq (cells, nuclei), scATAC-seq, and scMethylation-seq.
