### ISSUE TITLE
Deliver on partnership with CL

### ISSUE THREAD

**Issue by BAevermann** [chanzuckerberg/single-cell#633]
Currently in hiring process. 
Other deliverables include: 
1. Review Cell Guide definitions
2. Add x number of new terms
3. Begin manual review of Corpus uisng Pandasaurous 
4. Attendance at relevant jamborees

**Comment by brianraymor** [comment]
@BAevermann - I would recommend either creating a real task list in the top-level summary comment a'la:

- [ ] Review Cell Guide definitions
- [ ] Add x number of new terms
- [ ] Begin manual review of Corpus uisng Pandasaurous
- [ ] Attendance at relevant jamborees

and/or using child issues for each to share progress.

**Comment by BAevermann** [comment]
This ticket seems a bit redundant as the above indicators are tracked and reviewed via the grant reporting mechanism. I am going to close this unless there is a motivating case to bring additional visibility here...
